import type { FinanceConfig } from "./types";

export const DEFAULT_CONFIG: FinanceConfig = {
  loan: {
    currentBalance: 442_635.68,
    earlyPayment: 30000,
    mandatoryPayment: 25000,
    startBalance: 480000,
    startDate: "2026-05-12",
  },
  payments: [
    {
      id: "claude",
      name: "Claude",
      icon: "bot",
      amount: 2000,
      period: "salary",
      dayOfMonth: 15,
      description: "15-го числа",
    },
    {
      id: "phone",
      name: "Телефон T2",
      icon: "smartphone",
      amount: 750,
      period: "salary",
      dayOfMonth: 16,
      description: "16-го числа",
    },
    {
      id: "utilities",
      name: "Коммуналка",
      icon: "plug",
      amount: 7000,
      period: "salary",
      dayOfMonth: 18,
      description: "18-го числа",
    },
    {
      id: "yadrive",
      name: "Я.Драйв Клуб",
      icon: "car",
      amount: 700,
      period: "salary",
      dayOfMonth: 25,
      description: "25–26 числа",
    },
    {
      id: "yaplus",
      name: "Я.Плюс",
      icon: "star",
      amount: 425,
      period: "salary",
      dayOfMonth: 27,
      description: "27-го числа",
    },
    {
      id: "vpn",
      name: "ВПН",
      icon: "globe",
      amount: 600,
      period: "salary",
      dayOfMonth: 28,
      description: "28–29 числа",
    },
    {
      id: "loan-early",
      name: "Кредит (досрочный)",
      icon: "zap",
      amount: 30000,
      period: "salary",
      dayOfMonth: 15,
      description: "С зарплаты сразу",
    },
    {
      id: "internet",
      name: "Домашний интернет",
      icon: "home",
      amount: 1000,
      period: "advance",
      dayOfMonth: 1,
      description: "1-го числа",
    },
    {
      id: "loan-mandatory",
      name: "Кредит (обязательный)",
      icon: "landmark",
      amount: 25000,
      period: "advance",
      dayOfMonth: 2,
      description: "2-го числа",
    },
  ],
  paymentChecks: {},
  carsharingTags: [
    { id: "tag-home-work", name: "Дом → Работа" },
    { id: "tag-work-home", name: "Работа → Дом" },
    { id: "tag-metro-home", name: "Метро → Дом" },
    { id: "tag-home-metro", name: "Дом → Метро" },
  ],
  carsharingTrips: [],
};
