/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PotsRouteImport } from './routes/pots'
import { Route as PeriodsRouteImport } from './routes/periods'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PotsRoute = PotsRouteImport.update({
  id: '/pots',
  path: '/pots',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loan': typeof LoanRoute
  '/periods': typeof PeriodsRoute
  '/pots': typeof PotsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loan': typeof LoanRoute
  '/periods': typeof PeriodsRoute
  '/pots': typeof PotsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loan': typeof LoanRoute
  '/periods': typeof PeriodsRoute
  '/pots': typeof PotsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loan' | '/periods' | '/pots' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loan' | '/periods' | '/pots' | '/settings'
  id: '__root__' | '/' | '/loan' | '/periods' | '/pots' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoanRoute: typeof LoanRoute
  PeriodsRoute: typeof PeriodsRoute
  PotsRoute: typeof PotsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pots': {
      id: '/pots'
      path: '/pots'
      fullPath: '/pots'
      preLoaderRoute: typeof PotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoanRoute: LoanRoute,
  PeriodsRoute: PeriodsRoute,
  PotsRoute: PotsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
